import re

with open('js/blog-data.js', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "type: 'Interview'": "type: 'Entrevista'",
    "type: 'Review'": "type: 'Reseña'",
    "type: 'Reflection'": "type: 'Reflexión'",
    "type: 'Casual'": "type: 'Casual'",
    
    # Article 1
    "'Dialogue with Wisdom: A Conversation on the Inner Journey'": "'Diálogo con la Sabiduría: Una Conversación sobre el Viaje Interior'",
    "'A deep interview about the spiritual path and the search for meaning in modern life.'": "'Una profunda entrevista sobre el camino espiritual y la búsqueda de sentido en la vida moderna.'",
    "What is the fundamental purpose of the spiritual journey?": "¿Cuál es el propósito fundamental del viaje espiritual?",
    "The fundamental purpose is union with the Divine. As the Sri Guru Granth Sahib teaches, true purpose is found in remembering the Divine Name. This is not about escaping the world, but about finding harmony between the material and the spiritual.": "El propósito fundamental es la unión con lo Divino. Como enseña el Sri Guru Granth Sahib, el verdadero propósito se encuentra en recordar el Nombre Divino. No se trata de escapar del mundo, sino de encontrar la armonía entre lo material y lo espiritual.",
    "How can we sustain spiritual practice in daily life?": "¿Cómo podemos sostener la práctica espiritual en la vida diaria?",
    "Practice does not require isolation. Every action can become an offering when performed with awareness. The Guru teaches that meditation can be present in every moment, in every breath, in every act of service.": "La práctica no requiere aislamiento. Cada acción puede convertirse en una ofrenda cuando se realiza con conciencia. El Guru enseña que la meditación puede estar presente en cada momento, en cada respiración, en cada acto de servicio.",
    "What role does community play in spiritual growth?": "¿Qué papel juega la comunidad en el crecimiento espiritual?",
    "Sangat, the spiritual community, is essential. We do not walk alone. In the company of elevated souls, we find inspiration and support. \"In the company of the saints, one becomes saintly.\" It is a collective journey toward illumination.": "El Sangat, la comunidad espiritual, es esencial. No caminamos solos. En compañía de almas elevadas, encontramos inspiración y apoyo. \"En la compañía de los santos, uno se vuelve santo.\" Es un viaje colectivo hacia la iluminación.",
    "How do we face doubts and moments of darkness?": "¿Cómo enfrentamos las dudas y los momentos de oscuridad?",
    "Doubts are part of the process. The Guru reminds us that even in the deepest darkness, the light of the Divine Name is present. Steady practice, scripture reading, and meditation are our tools for passing through these moments.": "Las dudas son parte del proceso. El Guru nos recuerda que incluso en la oscuridad más profunda, la luz del Nombre Divino está presente. La práctica constante, la lectura de escrituras y la meditación son nuestras herramientas para atravesar estos momentos.",

    # Article 2
    "'Voices of the Present: Reflections on Faith in the Digital Era'": "'Voces del Presente: Reflexiones sobre la Fe en la Era Digital'",
    "'Exploring how ancestral teachings find their place in a digitally connected world.'": "'Explorando cómo las enseñanzas ancestrales encuentran su lugar en un mundo digitalmente conectado.'",
    "How does modern technology affect our spiritual practice?": "¿Cómo afecta la tecnología moderna a nuestra práctica espiritual?",
    "Technology is neutral; it depends on how we use it. It can be a powerful tool to connect with spiritual communities, access teachings, and maintain a steady practice. Yet it can also distract us if we do not keep discipline.": "La tecnología es neutral; depende de cómo la usemos. Puede ser una herramienta poderosa para conectar con comunidades espirituales, acceder a enseñanzas y mantener una práctica constante. Sin embargo, también puede distraernos si no mantenemos la disciplina.",
    "Is it possible to find moments of silence in such a noisy world?": "¿Es posible encontrar momentos de silencio en un mundo tan ruidoso?",
    "Absolutely. Silence does not require the absence of external sound, but inner stillness. We can create sacred spaces anywhere: during a commute, in a pause at work, upon waking. The Guru teaches that the Divine Name is always available, regardless of external circumstances.": "Absolutamente. El silencio no requiere la ausencia de sonido externo, sino quietud interior. Podemos crear espacios sagrados en cualquier lugar: durante un viaje, en una pausa en el trabajo, al despertar. El Guru enseña que el Nombre Divino siempre está disponible, independientemente de las circunstancias externas.",
    "What advice would you give to those beginning their spiritual path?": "¿Qué consejo le darías a quienes comienzan su camino espiritual?",
    "Start with patience and compassion toward yourself. Do not seek instant perfection. As the Guru says, \"Little by little, drop by drop, the heart fills with love.\" Consistency in practice is more valuable than occasional intensity. And remember: each day is a new opportunity.": "Comienza con paciencia y compasión hacia ti mismo. No busques la perfección instantánea. Como dice el Guru, \"Poco a poco, gota a gota, el corazón se llena de amor\". La constancia en la práctica es más valiosa que la intensidad ocasional. Y recuerda: cada día es una nueva oportunidad.",

    # Article 3
    "'Review: \"The Path of Devotion\" - An Album That Transcends'": "'Reseña: \"El Camino de la Devoción\" - Un Álbum que Trasciende'",
    "'A musical exploration of the depths of Bhakti and divine connection through sound.'": "'Una exploración musical de las profundidades del Bhakti y la conexión divina a través del sonido.'",
    "This album represents an extraordinary synthesis between devotional musical tradition and contemporary expressions. Each track invites deep inner reflection.": "Este álbum representa una síntesis extraordinaria entre la tradición musical devocional y las expresiones contemporáneas. Cada pista invita a una profunda reflexión interior.",
    "Strengths": "Fortalezas",
    "Impeccable production that honors tradition": "Producción impecable que honra la tradición",
    "Lyrics that connect with the spiritual heart": "Letras que conectan con el corazón espiritual",
    "A rich variety of authentic instruments": "Una rica variedad de instrumentos auténticos",
    "Arrangements that invite meditation": "Arreglos que invitan a la meditación",
    "Areas to Improve": "Áreas de Mejora",
    "Some tracks could be longer": "Algunas pistas podrían ser más largas",
    "Some verse translations could be deeper": "Algunas traducciones de versos podrían ser más profundas",
    "Overall, \"The Path of Devotion\" offers a transformative sonic experience that transcends entertainment to become a tool for spiritual growth. Highly recommended for those seeking music that nourishes the soul.": "En general, \"El Camino de la Devoción\" ofrece una experiencia sonora transformadora que trasciende el entretenimiento para convertirse en una herramienta de crecimiento espiritual. Altamente recomendado para aquellos que buscan música que nutra el alma.",

    # Article 4
    "'Analysis: \"Reflections of the Soul\" - Modern Spiritual Literature'": "'Análisis: \"Reflexiones del Alma\" - Literatura Espiritual Moderna'",
    "'A critical examination of a literary work that bridges ancient wisdom and contemporary consciousness.'": "'Un examen crítico de una obra literaria que tiende un puente entre la sabiduría antigua y la conciencia contemporánea.'",
    "\"Reflections of the Soul\" is a collection of essays that addresses spiritual themes from a perspective accessible to modern readers. The author demonstrates deep knowledge of sacred traditions while presenting them in a contemporary voice.": "\"Reflexiones del Alma\" es una colección de ensayos que aborda temas espirituales desde una perspectiva accesible para los lectores modernos. El autor demuestra un profundo conocimiento de las tradiciones sagradas mientras las presenta con una voz contemporánea.",
    "Clear, accessible language without losing depth": "Lenguaje claro y accesible sin perder profundidad",
    "Excellent references to the Sri Guru Granth Sahib": "Excelentes referencias al Sri Guru Granth Sahib",
    "A structure suited to both short and continuous reading": "Una estructura adecuada tanto para lecturas cortas como continuas",
    "Reflective questions at the end of each chapter": "Preguntas de reflexión al final de cada capítulo",
    "Considerations": "Consideraciones",
    "Some chapters could go deeper": "Algunos capítulos podrían profundizar más",
    "Footnotes for additional references are missing": "Faltan notas al pie para referencias adicionales",
    "This work serves as an excellent introduction for those approaching spiritual teachings for the first time, while also offering new perspectives for more experienced practitioners. The integration of theory and personal practice makes this book a valuable addition to any spiritual library.": "Esta obra sirve como una excelente introducción para aquellos que se acercan a las enseñanzas espirituales por primera vez, al tiempo que ofrece nuevas perspectivas para los practicantes más experimentados. La integración de la teoría y la práctica personal hace de este libro una valiosa adición a cualquier biblioteca espiritual.",

    # Article 5
    "'Silence as Teacher: Learning to Listen'": "'El Silencio como Maestro: Aprendiendo a Escuchar'",
    "'A meditation on the power of silence and inner listening in our spiritual journey.'": "'Una meditación sobre el poder del silencio y la escucha interior en nuestro viaje espiritual.'",
    "In a world filled with constant noise, finding silence can feel like an unreachable luxury. Yet silence is not the absence of sound, but the presence of deep attention.": "En un mundo lleno de ruido constante, encontrar el silencio puede parecer un lujo inalcanzable. Sin embargo, el silencio no es la ausencia de sonido, sino la presencia de una atención profunda.",
    "\"In the silence of meditation, the soul speaks and the heart listens to the Guru's voice.\"": "\"En el silencio de la meditación, el alma habla y el corazón escucha la voz del Guru.\"",
    "The Guru Granth Sahib teaches that true wisdom arises when we quiet external and internal voices. This is not a passive act, but an active state of receptivity where divine intuition can flow freely.": "El Guru Granth Sahib enseña que la verdadera sabiduría surge cuando silenciamos las voces externas e internas. Este no es un acto pasivo, sino un estado activo de receptividad donde la intuición divina puede fluir libremente.",
    "In my own practice, I have found that the most transformative moments occur not when I seek answers actively, but when I sit in silence and allow the teachings to sink in naturally. It is like watering a seed: we do not force it to grow, we simply provide the right conditions.": "En mi propia práctica, he descubierto que los momentos más transformadores ocurren no cuando busco respuestas activamente, sino cuando me siento en silencio y permito que las enseñanzas se asienten de forma natural. Es como regar una semilla: no la forzamos a crecer, simplemente proporcionamos las condiciones adecuadas.",
    "\"Quiet the mind, and in that silence you will find the One who is closer than your very breath.\"": "\"Aquieta la mente y en ese silencio encontrarás a Aquel que está más cerca que tu propia respiración.\"",
    "Silence teaches patience. In modern culture, we value speed and efficiency, but spiritual growth follows its own rhythm. Like the seasons, we cannot hurry inner flowering. We must learn to trust the process and honor each stage of the journey.": "El silencio enseña paciencia. En la cultura moderna, valoramos la velocidad y la eficiencia, pero el crecimiento espiritual sigue su propio ritmo. Al igual que las estaciones, no podemos apresurar el florecimiento interior. Debemos aprender a confiar en el proceso y honrar cada etapa del viaje.",
    "Practice for today: devote five minutes to conscious silence. Do not actively meditate; simply sit and listen. Let thoughts arrive and depart without clinging. In that space, find the presence that has always been there, waiting to be recognized.": "Práctica para hoy: dedica cinco minutos al silencio consciente. No medites activamente; simplemente siéntate y escucha. Deja que los pensamientos lleguen y se vayan sin aferrarte a ellos. En ese espacio, encuentra la presencia que siempre ha estado ahí, esperando ser reconocida.",

    # Article 6
    "'Service as an Expression of Divine Love'": "'El Servicio como Expresión de Amor Divino'",
    "'Reflecting on how Seva (selfless service) becomes a transformative spiritual practice.'": "'Reflexionando sobre cómo el Seva (servicio desinteresado) se convierte en una práctica espiritual transformadora.'",
    "Selfless service, or Seva, is not simply doing good deeds. It is a profound spiritual practice that transforms both the one who serves and the one who receives.": "El servicio desinteresado, o Seva, no es simplemente hacer buenas acciones. Es una profunda práctica espiritual que transforma tanto al que sirve como al que recibe.",
    "\"Selfless service is the most direct path to Self-realization. In the act of giving, we find ourselves.\"": "\"El servicio desinteresado es el camino más directo hacia la autorrealización. En el acto de dar, nos encontramos a nosotros mismos.\"",
    "I have observed that when we serve with expectations, when we seek recognition or gratitude, the act loses its transformative power. True Seva occurs when we forget we are serving, when the ego dissolves and only the act itself remains, pure and without labels.": "He observado que cuando servimos con expectativas, cuando buscamos reconocimiento o gratitud, el acto pierde su poder transformador. El verdadero Seva ocurre cuando olvidamos que estamos sirviendo, cuando el ego se disuelve y solo queda el acto en sí, puro y sin etiquetas.",
    "The Guru teaches that each being is a manifestation of the Divine. Therefore, when we serve another, we are truly serving that One Presence that dwells in all. This understanding completely changes the nature of service.": "El Guru enseña que cada ser es una manifestación de lo Divino. Por lo tanto, cuando servimos a otro, estamos sirviendo verdaderamente a esa Única Presencia que mora en todos. Esta comprensión cambia completamente la naturaleza del servicio.",
    "\"There is no difference between serving God and serving humanity. Both are expressions of the same unconditional love.\"": "\"No hay diferencia entre servir a Dios y servir a la humanidad. Ambos son expresiones del mismo amor incondicional.\"",
    "In my experience, service has been one of my greatest teachers. It has taught me humility when I realized how much I have received compared to how little I have given. It has taught me gratitude as I recognize my privileges. And above all, it has taught me love by showing me that serving is simply love in action.": "En mi experiencia, el servicio ha sido uno de mis grandes maestros. Me ha enseñado humildad al darme cuenta de cuánto he recibido en comparación con lo poco que he dado. Me ha enseñado gratitud al reconocer mis privilegios. Y sobre todo, me ha enseñado el amor al mostrarme que servir es simplemente amor en acción.",
    "Service does not require grand gestures. It can be listening to someone who needs to be heard, offering a genuine smile, helping without anyone knowing, or simply being present for another human being. In these small acts, we find the greatness of the spirit.": "El servicio no requiere grandes gestos. Puede ser escuchar a alguien que necesita ser escuchado, ofrecer una sonrisa genuina, ayudar sin que nadie lo sepa o simplemente estar presente para otro ser humano. En estos pequeños actos encontramos la grandeza del espíritu.",
    "Invitation: this week, seek an opportunity to serve without anyone knowing and without expecting anything in return. Observe how this simple act transforms your perspective and your relationship with the world.": "Invitación: esta semana, busca una oportunidad para servir sin que nadie lo sepa y sin esperar nada a cambio. Observa cómo este simple acto transforma tu perspectiva y tu relación con el mundo.",

    # Article 7
    "'The Sun Card: Illumination and Inner Clarity'": "'La Carta del Sol: Iluminación y Claridad Interior'",
    "'Exploring the symbolism of the Sun card in the context of our personal spiritual awakening.'": "'Explorando el simbolismo de la carta del Sol en el contexto de nuestro despertar espiritual personal.'",
    "The Sun card represents one of the highest states of consciousness on the spiritual journey. It is not sudden illumination, but the gradual recognition of the light that has always been present within us.": "La carta del Sol representa uno de los estados más elevados de conciencia en el viaje espiritual. No es una iluminación repentina, sino el reconocimiento gradual de la luz que siempre ha estado presente dentro de nosotros.",
    "In the context of spiritual teachings, this card reminds us of the Guru's words: \"The divine light dwells in every heart, yet few recognize it.\" The Sun is not something we need to seek outside; it is our true nature, temporarily obscured by the clouds of ignorance and ego.": "En el contexto de las enseñanzas espirituales, esta carta nos recuerda las palabras del Guru: \"La luz divina mora en cada corazón, sin embargo pocos la reconocen\". El Sol no es algo que debamos buscar afuera; es nuestra verdadera naturaleza, oscurecida temporalmente por las nubes de la ignorancia y el ego.",
    "When this card appears in a reading, it may indicate a period of clarity and deep understanding. It is a moment to trust our intuition, to let our true essence shine without restriction.": "Cuando esta carta aparece en una lectura, puede indicar un período de claridad y profunda comprensión. Es un momento para confiar en nuestra intuición, para dejar que nuestra verdadera esencia brille sin restricciones.",
    "Solar symbolism connects with many spiritual traditions. In many teachings, the sun represents the Atman, the true Self that transcends the limitations of the individual ego. It is pure, eternal, radiant consciousness.": "El simbolismo solar se conecta con muchas tradiciones espirituales. En muchas enseñanzas, el sol representa el Atman, el verdadero Ser que trasciende las limitaciones del ego individual. Es conciencia pura, eterna y radiante.",
    "In our daily practice, we can invoke the energy of the Sun through morning meditation, allowing the first rays to remind us of our own luminous nature. It is not a complex ritual, but a simple practice of recognition and gratitude.": "En nuestra práctica diaria, podemos invocar la energía del Sol a través de la meditación matutina, permitiendo que los primeros rayos nos recuerden nuestra propia naturaleza luminosa. No es un ritual complejo, sino una simple práctica de reconocimiento y gratitud.",

    # Article 8
    "'The Star: Hope and Guidance in Dark Moments'": "'La Estrella: Esperanza y Guía en Momentos Oscuros'",
    "'A casual reflection on how the Star card guides us in times of spiritual uncertainty.'": "'Una reflexión casual sobre cómo la carta de la Estrella nos guía en tiempos de incertidumbre espiritual.'",
    "The Star is one of the most comforting cards in spiritual tarot. After the turbulence represented by the Tower, the Star emerges as a beacon of hope in the dark night of the soul.": "La Estrella es una de las cartas más reconfortantes del tarot espiritual. Después de la turbulencia representada por la Torre, la Estrella emerge como un faro de esperanza en la noche oscura del alma.",
    "This card speaks of renewed faith, of the ability to find meaning even in the most difficult moments. The Guru reminds us: \"In the deepest darkness, the light of a single star is enough to find the path.\"": "Esta carta habla de fe renovada, de la capacidad de encontrar significado incluso en los momentos más difíciles. El Guru nos recuerda: \"En la oscuridad más profunda, la luz de una sola estrella es suficiente para encontrar el camino.\"",
    "The Star also represents spiritual inspiration, that divine spark that moves us forward when everything seems lost. It is the inner voice that whispers that we are greater than our circumstances, that our essence transcends temporary challenges.": "La Estrella también representa la inspiración espiritual, esa chispa divina que nos impulsa hacia adelante cuando todo parece perdido. Es la voz interior que nos susurra que somos más grandes que nuestras circunstancias, que nuestra esencia trasciende los desafíos temporales.",
    "In practical terms, the appearance of this card suggests it is time to connect with our inner source of inspiration. It may be through reading sacred scriptures, meditation, or simply contemplating the beauty of the night sky.": "En términos prácticos, la aparición de esta carta sugiere que es hora de conectar con nuestra fuente interna de inspiración. Puede ser a través de la lectura de escrituras sagradas, la meditación o simplemente contemplando la belleza del cielo nocturno.",
    "The Star teaches us that even in the darkest periods of our spiritual life, guidance is available. We only need to learn to look upward, to trust that light always returns, and to remember that stars are most visible when the night is darkest.": "La Estrella nos enseña que incluso en los períodos más oscuros de nuestra vida espiritual, hay guía disponible. Solo necesitamos aprender a mirar hacia arriba, a confiar en que la luz siempre regresa, y a recordar que las estrellas son más visibles cuando la noche es más oscura."
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open('js/blog-data.js', 'w', encoding='utf-8') as f:
    f.write(content)
